import sequelize from "../config/db.js";
import Order from "../models/order.model.js";
import OrderDetail from "../models/order_detail.model.js";
import Product from "../models/product.model.js";
import Customer from "../models/user.model.js";
import UserAddress from "../models/user_address.model.js";
import ShoppingCartItem from "../models/shopping_cart_item.model.js";

/**
 * Create order with items, validate stock, deduct inventory
 * POST /orders/create
 */
export const createOrder = async ({
  user_id,
  items, // [{ product_id, quantity }]
  shipping_address_id,
  shipping_address,
  payment_method,
  recipient_name,
  recipient_phone,
}) => {
  const transaction = await sequelize.transaction();

  try {
    // Step 1: Validate input
    if (!user_id || !items || items.length === 0) {
      throw {
        code: "INVALID_INPUT",
        message: "Vui lòng cung cấp user_id và ít nhất 1 sản phẩm",
      };
    }

    const trimmedRecipientName =
      typeof recipient_name === "string" ? recipient_name.trim() : "";
    const trimmedRecipientPhone =
      typeof recipient_phone === "string" ? recipient_phone.trim() : "";

    if (!trimmedRecipientName) {
      throw {
        code: "INVALID_INPUT",
        message: "Vui lòng nhập họ tên người nhận",
      };
    }

    if (!trimmedRecipientPhone) {
      throw {
        code: "INVALID_INPUT",
        message: "Vui lòng nhập số điện thoại người nhận",
      };
    }

    // Check customer exists
    const customer = await Customer.findByPk(user_id, { transaction });
    if (!customer) {
      throw { code: "CUSTOMER_NOT_FOUND", message: "Khách hàng không tồn tại" };
    }

    // Resolve shipping address
    const normalizedShippingText =
      typeof shipping_address === "string" ? shipping_address.trim() : "";
    let shippingAddressStr = normalizedShippingText || null;

    const normalizedAddressId = Number.isFinite(Number(shipping_address_id))
      ? Number(shipping_address_id)
      : null;

    if (!shippingAddressStr && normalizedAddressId) {
      const address = await UserAddress.findOne({
        where: { address_id: normalizedAddressId, user_id },
        transaction,
      });

      if (!address) {
        throw {
          code: "INVALID_ADDRESS",
          message: "Địa chỉ giao hàng không hợp lệ",
        };
      }

      const parts = [
        address.address_line,
        address.ward,
        address.district,
        address.province,
      ].filter(Boolean);
      shippingAddressStr = parts.join(", ");
    }

    if (!shippingAddressStr) {
      throw {
        code: "INVALID_ADDRESS",
        message: "Vui lòng cung cấp địa chỉ giao hàng",
      };
    }

    const normalizedPaymentMethod =
      payment_method === "OnlineBanking" ? "OnlineBanking" : "Cash";

    // Step 2: Check stock for all products with FOR UPDATE lock
    const productIds = items.map((item) => item.product_id);
    const products = await Product.findAll({
      where: { product_id: productIds },
      transaction,
      lock: transaction.LOCK.UPDATE, // FOR UPDATE
    });

    const productMap = new Map(products.map((p) => [p.product_id, p]));

    // Validate each item
    const validatedItems = [];
    let totalAmount = 0;

    for (const item of items) {
      const product = productMap.get(item.product_id);

      if (!product) {
        throw {
          code: "PRODUCT_NOT_FOUND",
          product_id: item.product_id,
          message: `Sản phẩm ${item.product_id} không tồn tại`,
        };
      }

      if (product.stock < item.quantity) {
        throw {
          code: "INSUFFICIENT_QUANTITY",
          product_id: item.product_id,
          product_name: product.product_name,
          requested: item.quantity,
          available: product.stock,
          message: `Số lượng bạn chọn vượt quá số lượng tồn kho (Có sẵn: ${product.stock})`,
        };
      }

      const itemTotal = parseFloat(product.sale_price) * item.quantity;
      totalAmount += itemTotal;

      validatedItems.push({
        product_id: item.product_id,
        quantity: item.quantity,
        unit_price: product.sale_price,
        total_price: itemTotal,
      });
    }

    const orderedProductIds = [
      ...new Set(validatedItems.map((item) => item.product_id)),
    ];

    // Step 3: Create order record (order_code will be generated by trigger)
    const order = await Order.create(
      {
        customer_id: user_id,
        recipient_name: trimmedRecipientName,
        recipient_phone: trimmedRecipientPhone,
        shipping_address: shippingAddressStr,
        payment_method: normalizedPaymentMethod,
        total_amount: totalAmount,
        final_amount: totalAmount,
        // order_code will be NULL, trigger will populate it
      },
      { transaction }
    );

    // Step 4: Create order details
    for (const item of validatedItems) {
      await OrderDetail.create(
        {
          order_id: order.order_id,
          product_id: item.product_id,
          quantity: item.quantity,
          unit_price: item.unit_price,
          total_price: item.total_price,
        },
        { transaction }
      );
    }

    // Step 5: Deduct inventory
    for (const item of validatedItems) {
      await Product.decrement("stock", {
        by: item.quantity,
        where: { product_id: item.product_id },
        transaction,
      });
    }

    // Step 6: Remove ordered items from shopping cart inside the same transaction
    if (orderedProductIds.length > 0) {
      await ShoppingCartItem.destroy({
        where: {
          user_id,
          product_id: orderedProductIds,
        },
        transaction,
      });
    }

    // Commit transaction
    await transaction.commit();

    // Step 7: Generate order_code in application (avoid trigger lock issues)
    // Format: ORD20250130-000001
    const orderCode = `ORD${new Date()
      .toISOString()
      .slice(0, 10)
      .replace(/-/g, "")}-${String(order.order_id).padStart(6, "0")}`;
    await Order.update(
      { order_code: orderCode },
      { where: { order_id: order.order_id } }
    );

    // Step 8: Query order again to get updated order_code
    const createdOrder = await Order.findByPk(order.order_id, {
      include: [
        {
          model: OrderDetail,
          as: "orderDetails",
          include: [{ model: Product, as: "product" }],
        },
      ],
    });

    return {
      status: "success",
      order_id: createdOrder.order_id,
      order_code: createdOrder.order_code,
      total_amount: createdOrder.total_amount,
      final_amount: createdOrder.final_amount,
      items: createdOrder.orderDetails,
    };
  } catch (error) {
    await transaction.rollback();
    throw error;
  }
};

/**
 * Get orders by customer
 */
export const getOrdersByCustomer = async (user_id) => {
  const orders = await Order.findAll({
    where: { customer_id: user_id },
    include: [
      {
        model: OrderDetail,
        as: "orderDetails",
        include: [{ model: Product, as: "product" }],
      },
    ],
    order: [["created_at", "DESC"]],
  });

  return orders;
};

/**
 * Get order detail
 */
export const getOrderDetail = async (order_id) => {
  const order = await Order.findByPk(order_id, {
    include: [
      { model: Customer, as: "customer" },
      {
        model: OrderDetail,
        as: "orderDetails",
        include: [{ model: Product, as: "product" }],
      },
    ],
  });

  if (!order) {
    throw { code: "ORDER_NOT_FOUND", message: "Đơn hàng không tồn tại" };
  }

  return order;
};

/**
 * Update order status
 */
export const updateOrderStatus = async (order_id, order_status) => {
  const validStatuses = ["Preparing", "On delivery", "Delivered"];

  if (!validStatuses.includes(order_status)) {
    throw {
      code: "INVALID_STATUS",
      message: `Trạng thái đơn hàng phải là: ${validStatuses.join(", ")}`,
    };
  }

  const [updatedCount] = await Order.update(
    { order_status },
    { where: { order_id } }
  );

  if (updatedCount === 0) {
    throw { code: "ORDER_NOT_FOUND", message: "Đơn hàng không tồn tại" };
  }

  return { status: "success", message: "Cập nhật trạng thái thành công" };
};

/**
 * Update payment status
 */
export const updatePaymentStatus = async (order_id, payment_status) => {
  const validStatuses = ["Unpaid", "Paid"];

  if (!validStatuses.includes(payment_status)) {
    throw {
      code: "INVALID_STATUS",
      message: `Trạng thái thanh toán phải là: ${validStatuses.join(", ")}`,
    };
  }

  const [updatedCount] = await Order.update(
    { payment_status },
    { where: { order_id } }
  );

  if (updatedCount === 0) {
    throw { code: "ORDER_NOT_FOUND", message: "Đơn hàng không tồn tại" };
  }

  return { status: "success", message: "Cập nhật thanh toán thành công" };
};
